### ISSUE TITLE
Adjust Sea Life spawn amount

### ISSUE THREAD

**Issue by draegon1993** [biomes-team/BiomesIslands#17]
The amount of sea life on the islands needs increased, the amount of animals seems spread between the island and the sea so it makes things very.... spread out.

**Comment by Zylleon** [comment]
Which islands?
Increased by about how much? (a little more, 5x as much)

**Comment by draegon1993** [comment]
All of them, let's try tripling it for now.

**Comment by Zylleon** [comment]
3x is a LOT. What are you basing that on?
Last time I checked, tropical islands already have about 20% more animals than tropical rainforests. I have not compared the other islands.

If the problem is "too many land animals" we can adjust the balance.
If the problem is "ocean looks empty", we should add more water plants imo. The land animals are also spread out, but the land looks less empty because it has lots of grass, bushes, trees etc.
If the problem is "I run out of animals to hunt much faster than on vanilla biomes", we should add bigger animals.
